import { createActions } from 'reduxsauce';

export const { Types, Creators } = createActions({
	// Notification
	setNotification: ['message', 'level'],
	clearNotification: null,
	// Auth & User
	loginAttempt: ['user'],
	loginAuthSuccess: ['auth', 'success'],
	loginUserSuccess: ['user', 'success'],
	loginFailure: ['error'],
	logout: null,
	forgotAttempt: ['email'],
	forgotSuccess: ['data', 'success'],
	forgotFailed: ['error'],
	resetAttempt: ['data'],
	resetSuccess: ['data', 'success'],
	resetFailed: ['error'],
	getUsersAttempt: null,
	getUsersSuccess: ['data'],
	getUsersFailure: null,
	registerAttempt: ['user'],
	registerSuccess: ['user', 'success'],
	registerFailure: ['error'],
	setSubscriptionType: ['data'],
	setAppointment: ['value'],
	bookingSuccess: ['booking', 'success'],
	bookingFailure: ['error'],
	getAppointmentRequest: null,
	getAppointmentSuccess: ['appointments', 'success'],
	getAppointmentFailed: ['error'],
	updateAppointmentStatusRequest: ['data'],
	updateAppointmentStatusSuccess: ['appointment', 'success'],
	updateAppointmentStatusFailed: ['error'],
	getUsersRequest: null,
	getUsersSuccess: ['users', 'success'],
	getUsersFailed: ['error'],
	getUserInfoRequest: ['userId'],
	getUserInfoSuccess: ['user', 'success'],
	getUserInfoFailed: ['error'],
	updateUserInfoRequest: ['data', 'userId'],
	updateUserInfoSuccess: ['user', 'success'],
	updateUserInfoFailed: ['error'],
	pickDate: ['data'],
	getBookingDatesRequest: null,
	getBookingDatesSuccess: ['bookings'],
	getBookingDatesFailed: ['error'],
	confirmAttempt: ['token'],
	confirmSuccess: ['data', 'success'],
	confirmFailed: ['error'],
	updateUserProfileRequest: ['data', 'userId'],
	updateUserProfileSuccess: ['user', 'success'],
	updateUserProfileFailed: ['error'],
	cancelAppointmentRequest: ['id'],
	cancelAppointmentSuccess: ['data', 'success'],
	cancelAppointmentFailed: ['error'],
	setReschedule: null,
	sendEmailRequest: ['data'],
	sendEmailSuccess: ['data', 'success'],
	sendEmailFailed: ['error'],
	confirmRegisterAttempt: ['token'],
	confirmRegisterSuccess: ['data', 'success'],
	confirmRegisterFailed: ['error'],
	removeUserAppointment: null,
	setUserAppointment: ['booking', 'success'],
	getUserInfoSuccess: ['user']

})
